version: "2"

services:
  db:
    image: wodby/drupal-mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./mariadb:/var/lib/mysql
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here
#    ports:
#      - "3306:3306"

  app:
    image: wodby/drupal-php:7.0 # Allowed: 7.0, 5.6
    environment:
      XDEBUG_CONFIG: xdebug.remote_autostart=0 # Set 1 to enable Xdebug.
    volumes:
      - ./docroot:/var/www/html

  web:
    image: wodby/drupal-nginx
    environment:
      DRUPAL_VERSION: 8 # Allowed: 7, 8
    volumes_from:
      - app
    ports:
      - "8000:80"

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8001:80"

  smtp:
    image: junxy/docker-mailcatcher
    ports:
      - "8002:1080"

#  redis:
#    image: redis:3.2-alpine
#    ports:
#      - "6379:6379"

#  memcached:
#    image: memcached:1.4-alpine
#    ports:
#      - "11211:11211"

#  solr:
#    image: solr:5.5-alpine
#    volumes:
#      - ./solr:/opt/solr/server/solr/mycores
#    ports:
#      - "8983:8983"
