site_name: Docker4Drupal Documentation

repo_url: https://github.com/wodby/docker4drupal
site_description: 'Docker4Drupal – Docker-based Drupal environment for local development'
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: True

pages:
  - Getting started: 'index.md'
  - Performance on MacOS: 'macos.md'
  - Docroot in subdirectory: 'docroot.md'
  - Containers:
    - 'Basics': 'containers/index.md'
    - 'Nginx': 'containers/nginx.md'
    - 'PHP': 'containers/php.md'
    - 'MariaDB': 'containers/mariadb.md'
    - 'Redis': 'containers/redis.md'
    - 'Memcached': 'containers/memcached.md'
    - 'Apache Solr': 'containers/solr.md'
    - 'Varnish': 'containers/varnish.md'
    - 'Mailhog': 'containers/mailhog.md'
  - CI/CD: 'cicd.md'
  - Known Issues: 'known-issues.md'
  - Logs: 'logs.md'
  - Using In Production: 'production.md'
